title: Linh Le # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, Iâ€™m Linh! 

ğŸ’¡Think of me as a mix between a data detective, math-minded problem solver, insight translator, and lifelong learner. Currently seeking roles as a Data Analyst or Data Scientist.

âš’ï¸ Key Skills & Focus Areas:
- Data Analysis & Exploration â€“ Statistical analysis, data cleaning, and identifying actionable insights with Excel and R.
- SQL & Relational Databases â€“ Writing complex queries, joins, aggregations, and subqueries.
- Python for Data â€“ Libraries like pandas, numpy, matplotlib, seaborn for EDA and reporting.
- Data Visualization â€“ Building interactive dashboards with Tableau and Power BI.

ğŸ‘©â€ğŸ« From Teaching to Data - What I bring:
- A background in education means Iâ€™m naturally skilled at explaining complex ideas.
- Iâ€™m detail-oriented, organized, and always thinking about the end userâ€™s experience.
- Collaboration comes naturally - I thrive when working across teams to solve problems.

ğŸ§When Iâ€™m not playing with data, youâ€™ll probably find me in the kitchen testing out a new baking recipe. I love making things that are structured, beautiful, and satisfying.

âœ… Letâ€™s connect and chat about all things data, strategy, or even that that irresistible baking recipe you just perfected. Feel free to contact or refer me to any Data Analyst or Data Scientist roles.

My contact information is baolinh2511@gmail.com.  <br><br>
  <a href="https://www.linkedin.com/in/thibaolinhle/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

